name: Update branch github-pages

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  pull-main-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'nysominea'
          git config --global user.email 'sominea.ny77@gmail.com'

      - name: Pull changes from main to github-pages
        run: |
          git fetch origin
          git checkout github-pages
          git merge main
          git push origin github-pages
